export const theme = {
  colors: {
    background: 'var(--background)',
    foreground: 'var(--foreground)',
    card: 'var(--card)',
    cardForeground: 'var(--card-foreground)',
    popover: 'var(--popover)',
    popoverForeground: 'var(--popover-foreground)',
    primary: 'var(--primary)',
    primaryForeground: 'var(--primary-foreground)',
    secondary: 'var(--secondary)',
    secondaryForeground: 'var(--secondary-foreground)',
    muted: 'var(--muted)',
    mutedForeground: 'var(--muted-foreground)',
    accent: 'var(--accent)',
    accentForeground: 'var(--accent-foreground)',
    destructive: 'var(--destructive)',
    destructiveForeground: 'var(--destructive-foreground)',
    border: 'var(--border)',
    input: 'var(--input)',
    ring: 'var(--ring)',
    chart1: '#3d6b4f',
    chart2: '#c17f4e',
    chart3: '#8b9a84',
    chart4: '#d4c8b8',
    chart5: '#6b6560',
  },
  fonts: {
    sans: 'var(--font-dm-sans), system-ui, sans-serif',
    serif: "var(--font-playfair), 'Georgia', serif",
    mono: "'Geist Mono', monospace",
  },
  radius: {
    sm: '0.5rem',
    md: '0.625rem',
    lg: '0.75rem',
    xl: '1rem',
    '2xl': '1.5rem',
    '3xl': '2rem',
    full: '9999px',
  },
  spacing: {
    0: '0',
    1: '0.25rem',
    2: '0.5rem',
    3: '0.75rem',
    4: '1rem',
    5: '1.25rem',
    6: '1.5rem',
    8: '2rem',
    10: '2.5rem',
    12: '3rem',
    14: '3.5rem',
    16: '4rem',
    20: '5rem',
    24: '6rem',
    32: '8rem',
  },
  fontSize: {
    xs: ['0.75rem', { lineHeight: '1rem' }],
    sm: ['0.875rem', { lineHeight: '1.25rem' }],
    base: ['1rem', { lineHeight: '1.5rem' }],
    lg: ['1.125rem', { lineHeight: '1.75rem' }],
    xl: ['1.25rem', { lineHeight: '1.75rem' }],
    '2xl': ['1.5rem', { lineHeight: '2rem' }],
    '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
    '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
    '5xl': ['3rem', { lineHeight: '1' }],
    '6xl': ['3.75rem', { lineHeight: '1' }],
    '7xl': ['4.5rem', { lineHeight: '1' }],
    '8xl': ['6rem', { lineHeight: '1' }],
    '9xl': ['8rem', { lineHeight: '1' }],
  },
  shadows: {
    sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
    md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
    lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
    xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
  },
  // ─── Surface effects ──────────────────────────────────────────────────────
  glass: {
    background: 'var(--glass-bg)',
    border: 'var(--glass-border)',
    shadow: 'var(--glass-shadow)',
    inset: 'var(--glass-inset)',
    blur: 'blur(14px) saturate(1.4)',
  },
  clay: {
    // Primary (green) — for main action buttons
    primaryBg: 'linear-gradient(145deg, oklch(0.52 0.12 155), oklch(0.38 0.12 155))',
    primaryShadow: [
      '6px 6px 14px rgba(0,0,0,0.18)',
      '-3px -3px 8px var(--clay-highlight)',
      'inset 2px 2px 6px var(--clay-highlight)',
      'inset -3px -3px 8px var(--clay-depth)',
    ].join(', '),
    // Danger (red) — for recording-active state
    dangerBg: 'linear-gradient(145deg, #ef4444, #b91c1c)',
    dangerShadow: [
      '6px 6px 14px rgba(220,38,38,0.28)',
      '-3px -3px 8px var(--clay-highlight)',
      'inset 2px 2px 6px var(--clay-highlight)',
      'inset -3px -3px 8px rgba(0,0,0,0.22)',
    ].join(', '),
    // Pressed state (shared)
    pressedShadow: [
      '2px 2px 6px rgba(0,0,0,0.14)',
      '-1px -1px 4px var(--clay-highlight)',
      'inset 4px 4px 10px var(--clay-depth)',
      'inset -2px -2px 6px var(--clay-highlight)',
    ].join(', '),
    // Disabled state — flat, desaturated, no depth
    // Use when an action is unavailable (e.g. upload in progress).
    // The button should look "deflated" so users don't try to press it.
    disabledBg: 'linear-gradient(145deg, oklch(0.78 0.03 155), oklch(0.72 0.03 155))',
    disabledShadow: '0 2px 4px rgba(0,0,0,0.08)',
  },
  transitions: {
    fast: '150ms ease',
    normal: '300ms ease',
    slow: '500ms ease',
    verySlow: '700ms ease',
  },
  breakpoints: {
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
    '2xl': '1536px',
  },
} as const

export type Theme = typeof theme
